pipeline:
  identifier: Build_aiuaibulid_aiu_daily_1775566352299
  name: Build aiu-daily
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1775566183695
        repoName: aiuaibulid/aiu-daily
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    shell: Sh
                    command: echo "Harness CI is working"
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    shell: Sh
                    command: echo "Setup skipped"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
